name: CoMateDobreho
options:
  bundleIdPrefix: com.codobreho
  deploymentTarget:
    iOS: 11.0
  xcodeVersion: "12.3"
packages:
  Eureka:
    url: https://github.com/xmartlabs/Eureka
    version: 5.3.2
targets:
  CoMateDobrehoApp:
    type: application
    platform: iOS
    sources: [CoMateDobreho]
    dependencies:
      - package: Eureka
    info:
      path: CoMateDobreho/Info.plist
      properties:
        NSBluetoothAlwaysUsageDescription: "TODO"
        UISupportedInterfaceOrientations: [
          UIInterfaceOrientationPortrait,
          UIInterfaceOrientationPortraitUpsideDown,
          UIInterfaceOrientationLandscapeLeft,
          UIInterfaceOrientationLandscapeRight
        ]
    preBuildScripts:
      - script: "mint run swiftgen"
        name: SwiftGen
    postCompileScripts:
      - script: "mint run swiftformat . --swiftversion 5.3"
        name: SwiftFormat
      - script: "mint run swiftlint"
        name: SwiftLint
