name: CoMateDobreho
options:
  bundleIdPrefix: com.codobreho
  deploymentTarget:
    iOS: 9.0
  xcodeVersion: "12.3"
targets:
  CoMateDobrehoApp:
    type: application
    platform: iOS
    sources: [CoMateDobreho]
    info:
      path: CoMateDobreho/Info.plist
      properties:
        NSBluetoothAlwaysUsageDescription: "TODO"
    postCompileScripts:
      - script: swiftlint
        name: SwiftLint
      - script: "swiftformat . --swiftversion 5.3"
        name: SwiftFormat
